version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-s3www"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avr0ylgvc8ng"
s3_prefix = "sam-s3www"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"www-s3www\""
image_repositories = []
