AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-s3www

  s3 static www contents bucket example code

Parameters:
  BucketName:
    Type: String
    Default: www-s3www

Globals:
  Function:
    Timeout: 3

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete


Outputs:
  S3URL:
    Description: URL of S3 bucket to hold website content
    Value: !Sub "http://${S3Bucket}.s3-website-${AWS::Region}.amazonaws.com/"

  S3SecureURL:
    Description: Secure URL of S3 bucket to hold website content
    Value: !Sub "https://s3-${AWS::Region}.amazonaws.com/${S3Bucket}/index.html"
